### ISSUE TITLE
🔨 [refactor] jwt.strategy.ts

### ISSUE THREAD

**Issue by wth2052** [5g-FleaMarket/5g-fleamarket#56]
# 🔨 리팩토링이 필요한 부분 
jwt.strategy.ts 쪽에서 쿼리가 한번 더도는 식으로 설계가 되어있습니다.
이는 테스트 커버리지가 생각한 수준보다 더 낮게나올수 있는 안티 패턴이라 
생각되기에 리팩토링을 진행하게 되었습니다.
또한 저 방식으로 리턴이되면 검증된 리턴값에 패스워드도 담길것 입니다.
# 리팩토링 작업 브런치

refactor/jwtstrategy
### ✅ TODO

- [x] 쿼리 가 돌아 리턴을 하는방식이 아닌 payload 자체를 리턴시키기
이제 strategy에서 쿼리가 한번 더 돌지 않고, payload에서 id, email, nickname만을 리턴시키게 되었습니다.

# 😉 변경된 사항
![image](https://user-images.githubusercontent.com/55482454/224030364-bee7cfc6-4add-4535-9260-6edc011c6e6d.png)
![image](https://user-images.githubusercontent.com/55482454/224039067-0f34a9ba-28a4-4c0e-8d5a-804eea0daf29.png)
**-> 같은 JwtDecodeDto가 중복으로 정의되어있어 orders에 있는 DTO를 삭제후 user/dto/jwt-decode-dto.ts로 옮겼습니다**
  
**테스트 하다보니 가드가 없는쪽에서 페이로드를 찾지 못하는 이슈가 있었습니다.**
가드가 없을경우
![image](https://user-images.githubusercontent.com/55482454/224046007-edb28eeb-d31f-401a-8a6f-bf5a59f5f072.png)
orders 최상단에 @UseGuards(JwtAuthGuard)를 붙여 전역적으로 사용함으로써 해결하였습니다.
![image](https://user-images.githubusercontent.com/55482454/224047450-0a1a47e9-6a7b-4170-9371-8f698c28b3d2.png)

(상품 조회를 제외한 기타 페이로드 정보가 필요한곳에 전부 추가하였습니다.)

이제 토큰이 없는 사용자는 401, Unauthorized를 리턴합니다.

🐱‍👤 이번 Refactoring을 해서 얻는 이득 :
쓸모없는 트랜잭션 발생을 줄인다 ->
나중에 테스트에서 커버리지가 올라간다
-> 지구 평화가 찾아온다

**Comment by burno28** [comment]
유저가드 최고야 짜릿해 볼때마다 새로워
