### ISSUE TITLE
🔨 [refactor] 필독 : ★테이블 이름에 오타가 있습니다.★

### ISSUE THREAD

**Issue by wth2052** [5g-FleaMarket/5g-fleamarket#97]
# 🔨 리팩토링이 필요한 부분 
![image](https://user-images.githubusercontent.com/55482454/225214696-8e26cf9c-1656-4e2f-aa3c-f9dbe9e6acc2.png)
현재 발견한 오타입니다.
제가 예상하지 못한 곳에서 저 컬럼을 사용중 일수도 있어
제쪽에서 일괄 수정을 진행하지 않았습니다
수정 부탁드립니다.
@burno28 
@Seop0728 
@LeeHan098 
# 리팩토링 작업 브런치

TODO: 브랜치 따로 생성 하셔서 이쪽 이슈에 수정 부탁드립니다.

### ✅ TODO

- [ ] DB 엔티티 내 오타 수정/ 관련 코드 오타 수정

**Comment by Seop0728** [comment]
> # 🔨 리팩토링이 필요한 부분
> ![이미지](https://user-images.githubusercontent.com/55482454/225214696-8e26cf9c-1656-4e2f-aa3c-f9dbe9e6acc2.png) 현재 발견한 오타입니다.현재 발견한 오타입니다. 제가 예상하지 못한 곳에서 저 컬럼을 사용중 일수도 있어제가 예상하지 못한 곳에서 저 컬럼을 사용중 일수도 있어 제쪽에서 일괄 수정을 진행하지 않았습니다제쪽에서 일괄 수정을 진행하지 않았습니다 수정 부탁드립니다.수정 부탁드립니다. @burno28 @Seop0728 @LeeHan098
> 
> # 리팩토링 작업 브런치
> TODO: 브랜치 따로 생성 하셔서 이쪽 이슈에 수정 부탁드립니다.TODO: 브랜치 따로 생성 하셔서 이쪽 이슈에 수정 부탁드립니다.
> 
> ### ✅ 작업
> * [ ]  DB 엔티티 내 오타 수정/ 관련 코드 오타 수정DB 엔티티 내 오타 수정/ 관련 코드 오타 수정

![image](https://user-images.githubusercontent.com/110884476/225483115-e53247f8-8cd2-4044-a2ed-6b2a39eb9f7d.png)
해결되었습니다
